Repository scientific-python/docstub, pull requests merged in 2025-05, with the labels that each got.

#30 Add `--group-errors` option
  src/docstub/_cli.py
  src/docstub/_config.py
  src/docstub/_docstrings.py
  src/docstub/_stubs.py
  src/docstub/_utils.py
  tests/test_stubs.py
Labels: enhancement

#28 Support and default to inplace stub generation
  pyproject.toml
  src/docstub/_cli.py
  src/docstub/_stubs.py
Labels: enhancement

#33 Refactor and document doctype grammar
  src/docstub/_docstrings.py
  src/docstub/doctype.lark
Labels: documentation, maintenance

#34 Update import for Generator and Callable types
  src/docstub/_docstrings.py
  src/docstub/default_config.toml
  tests/test_docstrings.py
Labels: maintenance

#37 Fix grammar and allow plural "(s)"
  src/docstub/_docstrings.py
  src/docstub/doctype.lark
  tests/test_docstrings.py
Labels: enhancement

#40 fix check for length 1 literal
  src/docstub/_docstrings.py
Labels: fix

#45 Refactor configuration fields
  examples/docstub.toml
  examples/example_pkg/_basic.py
  pyproject.toml
  src/docstub/_analysis.py
  src/docstub/_cli.py
  src/docstub/_config.py
  src/docstub/_docstrings.py
  src/docstub/_stubs.py
  src/docstub/default_config.toml
  tests/test_analysis.py
  tests/test_config.py
Labels: maintenance

#41 Support combined NumPyDoc params
  src/docstub/_docstrings.py
  tests/test_docstrings.py
Labels: enhancement

#46 Allow signed numbers in literals
  src/docstub/doctype.lark
  tests/test_docstrings.py
Labels: fix

#51 Prepare release of version 0.3.0
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
  docs/release_notes/v0.2.0.md
  docs/release_notes/v0.3.0.md
  docs/user_guide.md
  pyproject.toml
Labels: devops

#52 Fix AttributeError for union of dtypes in array expression
  src/docstub/_docstrings.py
  tests/test_docstrings.py
Labels: fix

#53 Allow prefixing common known types with module name
  docs/user_guide.md
  examples/example_pkg-stubs/_basic.pyi
  examples/example_pkg-stubs/_numpy.pyi
  examples/example_pkg/_basic.py
  src/docstub/_analysis.py
  src/docstub/_cli.py
  tests/test_analysis.py
Labels: fix

#54 Fix broken diff check due to changed output behavior
  .github/workflows/ci.yml
Labels: devops
